### ISSUE TITLE
CRM mass flux variables are all zero

### ISSUE THREAD

**Issue by whannah1** [E3SM-Project/ACME-ECP#118]
I noticed this while examining some h0 file output for the INICTE2019 run. These variables are somehow not being populated correctly (although I haven't verified that all variables have this problem):

- SPMC
- SPMCUP
- SPMCDN
- SPMCUUP
- SPMCUDN

**Comment by lee1046** [comment]
wmin (minimum w for statistics) is set to 2m/s. The if  statement (line 912 in crm/crm_module.f90) - if(w(icrm,i,j,k+1)+w(icrm,i,j,k).gt.2*wmin) - may not give us True.

**Comment by whannah1** [comment]
False alarm, the data is ok.
